version: '3'

services:
  mysql_judge_backend:
    container_name: mysql_judge_backend
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: npm run dev
    networks:
      - sql-lab-server_sql_lab_network
    depends_on:
      - mysql_judge_db

  mysql_judge_db:
    image: mysql:8.0.37
    restart: always
    container_name: mysql_judge_db
    environment:
      MYSQL_ROOT_PASSWORD: SqlLab2024!
      MYSQL_DATABASE: base_issue_data
    networks:
      - sql-lab-server_sql_lab_network
    volumes:
      - ./docker-data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_db_data_v8:/var/lib/mysql

volumes:
  mysql_db_data_v8:

networks:
  sql-lab-server_sql_lab_network:
    external: true