- name: Add the user crvt4722
  user:
    name: crvt4722
    comment: Toi dz
    state: present
- name: Copy config files
  copy:
    src: /var/jenkins_home/workspace/MySQL_Judge_Service_main/ansible/roles/service/files
    dest: /home/crvt4722/

- name: Run docker-compose to create to database
  community.docker.docker_compose_v2:
    project_src: /home/crvt4722/files
    state: present

- name: Make sure database is started
  pause:
    seconds: 30

- name: Restart a judge server to reconnect to database
  docker_container:
    name: mysql_judge_backend
    state: started
    restart: yes
